// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdLara3cOHWuWKml68m_63p3-bLs9OtXM',
    appId: '1:640149722020:web:0ce902124cdbaafc99e731',
    messagingSenderId: '640149722020',
    projectId: 'prm393-group2',
    authDomain: 'prm393-group2.firebaseapp.com',
    storageBucket: 'prm393-group2.firebasestorage.app',
    measurementId: 'G-1J282GX4X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIvaJejXcr2e3ZTagoMoIrCGLspvAcwAQ',
    appId: '1:640149722020:android:2b202ec8faa4836a99e731',
    messagingSenderId: '640149722020',
    projectId: 'prm393-group2',
    storageBucket: 'prm393-group2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYSEAmBWhs1csMS56h2UwR1YiZjbniKZA',
    appId: '1:640149722020:ios:fb4cb69db6f28bfa99e731',
    messagingSenderId: '640149722020',
    projectId: 'prm393-group2',
    storageBucket: 'prm393-group2.firebasestorage.app',
    iosClientId: '640149722020-4b043f1o75hicmr0lvt4m2uu3jqc6l8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYSEAmBWhs1csMS56h2UwR1YiZjbniKZA',
    appId: '1:640149722020:ios:fb4cb69db6f28bfa99e731',
    messagingSenderId: '640149722020',
    projectId: 'prm393-group2',
    storageBucket: 'prm393-group2.firebasestorage.app',
    iosClientId: '640149722020-4b043f1o75hicmr0lvt4m2uu3jqc6l8h.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdLara3cOHWuWKml68m_63p3-bLs9OtXM',
    appId: '1:640149722020:web:55298c5bba20028799e731',
    messagingSenderId: '640149722020',
    projectId: 'prm393-group2',
    authDomain: 'prm393-group2.firebaseapp.com',
    storageBucket: 'prm393-group2.firebasestorage.app',
    measurementId: 'G-4H0WMW2N2V',
  );
}
